local COURSE_ACTS = smlua_text_utils_course_acts_replace
local SECRET_STAR = smlua_text_utils_secret_star_replace
local CASTLE_SECRET_STARS = smlua_text_utils_castle_secret_stars_replace
local EXTRA_TEXT = smlua_text_utils_extra_text_replace
COURSE_ACTS(COURSE_BOB, (" 1 DOUBTFUL CREEK TOWN"), 	("GOTTA GET UP THAT RAMP!"), 	("HIGH VIEW FROM THE DOOMED TOWN"), 	("SCHROOMY-KICK'S"), 	("CORRUPTED GRASS STROLL"), 	("SECRET TOAD HOUSE STASH"), 	("DEEP DIVE IN THE SEWERS -GB-"))

COURSE_ACTS(COURSE_WF, (" 2 FADING CITY"), 	("LOOMING OVER TOWN"), 	("THE BLOCKED PATHWAY"), 	("BREAK INTO THE HOUSE!"), 	("TOP TINY PARKOUR"), 	("FIND THE SQUID BEACON AGAIN!"), 	("DOWN THE CAGE! -GB-"))

COURSE_ACTS(COURSE_JRB, (" 3 FIRESTAR CANYON"), 	("BURNING LAKE'S TREASURE HUNT"), 	("FIERY ROUND RED"), 	("BUMPERS AND BLOCKS"), 	("ENTER THE RAVAGED TUNNEL -GB-"), 	("WHEN THE END IS ABOVE THE START -BB-"), 	("PILLARS OF PRECISION -BB-"))

COURSE_ACTS(COURSE_CCM, (" 4 TIMID DERPED TOWN"), 	("FLOWERY ARCH DOOM"), 	("HIGH VIEW"), 	("WALLKICK OR WALLJUMP? GET UP!"), 	("ON THE CLIFF SIDE"), 	("BOUNCING SECRETS"), 	("MYSTERIOUS PATH OF FLOWERS"))

COURSE_ACTS(COURSE_BBH, (" 5 ACIDIC MARSHLAND"), 	("A PINKY EXPEDITION"), 	("OH, THIS PATH IS BACKWARDS NOW"), 	("A TRIAL IN TOXICITY"), 	("CAN I WALLJUMP UP THERE?"), 	("BLASTING THROUGH THE TUNNEL -BB-"), 	("SLIDES. JUST SLIDES. -C3 EXIT-"))

COURSE_ACTS(COURSE_HMC, (" 6 FRIGID FACTORY"), 	("COIN ARROW FACTORY TOUR"), 	("FROZEN DOMAIN'S CURIOUS CUBE"), 	("THROUGH FROZEN PIPES AND MEMORIES"), 	("NAVIGATION UNDER THE ICE CRUST"), 	("AN UNCONVENTIONAL TOP ROUTE"), 	("CAREFUL FOOTING IN THE FACTORY"))

COURSE_ACTS(COURSE_LLL, (" 7 FROSTBITE SWAMP"), 	("THE TALL SHROOM"), 	("CRAZY 1-UP FEAST WITH LAVA"), 	("FROZEN SWAMP'S TREEHOUSE REMAINS"), 	("WHYNUT AT THE DARKNUT RUINS?"), 	("DECAYED HILL PATH"), 	("PERILOUS MONTAIN TOP"))

COURSE_ACTS(COURSE_SSL, (" 8 COLLAPSED MINES"), 	("THE CENTER BUILDING"), 	("INTENDED CHEESE?"), 	("BLAZING HOT LAVA"), 	("SIDES OF THE BUILDING"), 	("INFERNAL PANELS -GB-"), 	("IN THE WARP WALLS"))

COURSE_ACTS(COURSE_DDD, (" 9 ATROPHIED MANSION"), 	("A FLIGHT IN FENCE SIGHT!"), 	("WALLJUMPS BASICALLY DON'T WORK"), 	("THE CELLAR'S GOLD, I MEAN RED VAULT"), 	("ICE, CHAINS, AND MORE!"), 	("SIZZLING FLAMES' PATHWAY -GB-"), 	("RETURN TO THE ROOF -BB-"))

COURSE_ACTS(COURSE_SL, ("10 OMINOUS EXCAVATION TOWN"), 	("PYRAMIDAL RETURN"), 	("AROUND THE TOWN AND BEYOND"), 	("SLIPPERY HIGH-RISE"), 	("BOXES, POKEYS, AND MORE POKEYS"), 	("ONLY THE 37TH VERSION OF THIS TOWER"), 	("AN UNCONVENTIONAL CLIMB"))

COURSE_ACTS(COURSE_WDW, ("11 HEAT RASH CANYON"), 	("TIMED HOPPING BOX"), 	("TRIANGLE WALLJUMPS OF SWEAT"), 	("IN THE DARK ABYSS"), 	("BLASTING UP!"), 	("SECRET OF THE POLE CAVERN"), 	("HIDDEN IN SOMETHING GREEN"))

COURSE_ACTS(COURSE_TTM, ("12 THUNDER BLAZE HORIZON"), 	("THE CASTLE'S LEGACY"), 	("SPARK SLIDE REDS"), 	("THE TALLEST ROOM"), 	("SLIPPIN FRENZY"), 	("THUNDERBLASTED TOWN"), 	("TOXIC ZAPPY CAVE PANELS"))

COURSE_ACTS(COURSE_THI, ("13 PLAGUED CLIFFS"), 	("MECHANICAL REDS"), 	("CLIMB HIGH AND FALL BACK"), 	("VANISHING RACE QUICK!"), 	("SHELL SHENANIGANS -GB-"), 	("CANNON SHENANIGANS -BB-"), 	("ACROSS ALL BEYOND ALL -BB-"))

COURSE_ACTS(COURSE_TTC, ("14 MYSTIFIED MOUNTAINS"), 	("INVERTED COMPOSURE -BB-"), 	("JOURNEY THROUGH THE CAVERNS"), 	("LEFTOVER FOUNTAIN RELICS"), 	("AN UPSTAIRS STROLL"), 	("PLAYING WITH FIRE"), 	("THE STAR NEEDLE'S SUPER QUIZ"))

COURSE_ACTS(COURSE_RR, ("15 NIGHTSKY CITADEL"), 	("CLEAR SKY WALLJUMPS"), 	("AMP YOURSELF TO THE DARK SIDE OF THE MOON"), 	("SURFING IN THE NIGHT"), 	("STARBOUND ASCENSION REDS"), 	("SANDY BLAZING CAGE"), 	("DARK MOON RISING"))

SECRET_STAR(15+1, ("   BEAUTIFUL SKYSCAPE"))
SECRET_STAR(16+1, ("   FROZEN DIZZY PLANT"))
SECRET_STAR(17+1, ("   SCEPTER SANCTUM"))
SECRET_STAR(18+1, ("   THE REMNANT ABYSS"))
SECRET_STAR(19+1, ("   ECLIPSE OF A DUTISH PRISM"))
SECRET_STAR(20+1, ("   SWITCH PALACE"))
SECRET_STAR(21+1, ("   ECLIPSE OF A SIZZLING SUN"))
SECRET_STAR(22+1, ("   ECLIPSE OF A BLOODY MOON"))
SECRET_STAR(23+1, ("   NEEDLE BLUE REALM"))
SECRET_STAR(24+1, ("   THE REMNANT ABYSS"))
CASTLE_SECRET_STARS(("   SECRET STARS"))
EXTRA_TEXT(0,("ONE OF THE HIDDEN STARS!"))
EXTRA_TEXT(1,("YOU FOUND A RAINBOW STAR!"))
EXTRA_TEXT(2,(""))
EXTRA_TEXT(3,(""))
EXTRA_TEXT(4,(""))
EXTRA_TEXT(5,(""))
EXTRA_TEXT(6,(""))
