-- This file must be manually edited
set_exclamation_box_contents({
{ id = 0, unused = 14, firstByte = 14, model = 122, behavior = id_bhvWarp },
{ id = 1, unused = 0, firstByte = 0, model = E_MODEL_KOOPA_SHELL, behavior = id_bhvKoopaShell },
{ id = 2, unused = 0, firstByte = 0, model = E_MODEL_BOBOMB_BUDDY, behavior = id_bhvBobombBuddyOpensCannon },
{ id = 3, unused = 15, firstByte = 15, model = 122, behavior = id_bhvWarp },
{ id = 4, unused = 0, firstByte = 0, model = E_MODEL_MARIOS_CAP, behavior = id_bhvVanishCap },
{ id = 5, unused = 0, firstByte = 0, model = E_MODEL_MARIOS_METAL_CAP, behavior = id_bhvMetalCap },
{ id = 6, unused = 0, firstByte = 0, model = E_MODEL_NONE, behavior = id_bhvTenCoinsSpawn },
{ id = 7, unused = 0, firstByte = 0, model = E_MODEL_1UP, behavior = id_bhv1upWalking },
{ id = 8, unused = 0, firstByte = 0, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 9, unused = 0, firstByte = 0, model = E_MODEL_1UP, behavior = id_bhv1upRunningAway },
{ id = 10, unused = 0, firstByte = 1, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 11, unused = 0, firstByte = 2, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 12, unused = 0, firstByte = 3, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 13, unused = 0, firstByte = 4, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 14, unused = 0, firstByte = 6, model = E_MODEL_STAR, behavior = id_bhvSpawnedStar },
{ id = 15, unused = 0, firstByte = 0, model = E_MODEL_MARIOS_WING_CAP, behavior = id_bhvWingCap },
{ id = 16, unused = 0, firstByte = 0, model = E_MODEL_MARIOS_WING_CAP, behavior = id_bhvWingCap },
{ id = 17, unused = 0, firstByte = 0, model = E_MODEL_MARIOS_METAL_CAP, behavior = id_bhvMetalCap },
{ id = 18, unused = 0, firstByte = 0, model = E_MODEL_YELLOW_COIN, behavior = id_bhvSingleCoinGetsSpawned },
{ id = 19, unused = 0, firstByte = 0, model = E_MODEL_NONE, behavior = id_bhvThreeCoinsSpawn },
{ id = 20, unused = 0, firstByte = 0, model = 152, behavior = id_bhvWfBreakableWallRight },
{ id = 21, unused = 0, firstByte = 0, model = E_MODEL_KOOPA_SHELL, behavior = id_bhvKoopaShell },
})
warn("Custom exclamation boxes are incomplete! Correct them and then remove this line")