#include "model.inc.h"

const GeoLayout wiggler_body_geo[]= {
	GEO_SHADOW(1, 150, 100),
	GEO_OPEN_NODE(),
		GEO_SCALE(0, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(4, DL_wiggler_body_geo_0x500c278),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 65505, 0, 51, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, DL_wiggler_body_geo_0x500be98),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 39, 0, 0, DL_wiggler_body_geo_0x500be10),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 41, 0, 0, DL_wiggler_body_geo_0x500bcb8),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(1, 65505, 0, 65487, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 0, 0, 0, DL_wiggler_body_geo_0x500c100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 39, 0, 0, DL_wiggler_body_geo_0x500c078),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 41, 0, 0, DL_wiggler_body_geo_0x500bf20),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};